version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: laravel_user
            DB_PASSWORD: user_password

    db:
        image: mysql:8.0
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: user_password
        ports:
            - "3306:3306"
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
